### ISSUE TITLE
Player dashboard design using Bootstrap and Turbo

### ISSUE THREAD

**Issue by janpeterka** [bensheldon/spectator_sport#3]
Hi, I will gladly look into this and create some v1, if you want me to.

Questions:
- are you sure about using Bootstrap for this? I would go with pure css, not to add dependency here
- do you have any ideas on design you prefer? If it were up to me, I would probably do something similar to `solid_errors` interface (as shown in attachment). _It's build using some part of Tailwind, simply pasted into <style>, which seems reasonable to me_
![Screenshot from 2024-09-28 23-23-59](https://github.com/user-attachments/assets/d26688b5-3800-429e-bc54-c1255dd222d2)

- Turbo can be expected to be used in most Rails apps, so I can it can be used freely. Possible uses:
  - morphing by default for no-scrolling on change
  - `= turbo_stream_from` to update dashboard as new sessions are started?

**Comment by bensheldon** [comment]
Awesome! I really appreciate you jumping into this. Let me split this comment into two pieces just to not confuse what I'm talking about:

- Code for serving the assets (which I imagine being done similar to how GoodJob does it)
- The visual design (which I imagine will look different than GoodJob, cause Spectator Sport has a different purpose/functionality, but maybe not entirely cause it'll still look generally like Boostrap)

## Code for serving the assets

I feel pretty strongly about Bootstrap, if primarily because it's what I'm most familiar with, and a boringly complete design system.

Here's what GoodJob looks like: https://goodjob-demo.herokuapp.com/

I wanted Spectator Sport to be done similar to GoodJob, which I wrote about here: https://island94.org/2023/03/how-goodjob-s-mountable-rails-engine-delivers-javascript-importmaps-and-frontend-assets

It would be awesome if you could lift and copy implementation of what's in GoodJob (vendored file serving, importmaps). The only change I might do differently today would be to mount Rack::Files middleware in the Dashboard Engine rather than server via `render file:` from a controller.

## The visual design

Bare minimum, let's have a navbar and a table for the list of resources. And ship it!

Long term, I've always wanted to have a sidebar-based navigation that could slide out on mobile. But it's always eluded me to implement. I dunno if that is of interest to try (though definitely in follow-up
PRs, don't do this entire issue all at once)

Like this: https://getbootstrap.com/docs/5.3/examples/dashboard/

**Comment by bensheldon** [comment]
One thing about Turbo: I don't want to take turbo-rails as a gem dependency. I might change my mind in the future but:

- I don't trust that turbo-rails won't do weird stuff in the parent app, cause it installs stuff globally. 
- I don't trust that turbo-rails won't have some breaking changes that would tie down the parent app or break things because Spectator Sport is vendoring and using one version of the js and the parent app upgrades to a different version of the Ruby gem. 

So I'm imagining we might have to lift and copy a few of the turbo helper methods into the gem as we need them. And I'm assuming that will be simpler than managing dependencies with the parent app 🤞

**Comment by janpeterka** [comment]
Thanks for a thorough overview of the task and your view!

I realize this is your gem and your decision how to approach this, still I will try to explain why I would prefer alternative way. I don't want to make it an argument, just have this here and if you say that you still want it the "GoodJob" + Bootstrap way, I'll start working on it that way :)

In gem I'm currently creating I went with `gemname.css`, which is then manually included in app layout (can be a helper).
I use class based styling, namespaced for my gem (inspired by how [HotwireCombobox](https://github.com/josefarias/hotwire_combobox) does it) - eg. `spectator_sport-button` or something like that.
  
I see multiple benefits to this:
- there's no special assets serving, as this is only one simple static `css` file
  - _to be honest, I'm not yet sure how it works in GoodJob, and have no idea where to start with your suggested change with `Rack::Files`_ 
- no dependency, and changes that come with upgrading them
- it's small
- it's easily customizable, if users want to (not sure if we want that, so maybe not relevant?)

Only drawback I see is that it's more work to create it at the start (which the library does for us), and I'll be glad to work on that. I can even extract parts of bootstrap for the components to make it quick, and then we can tweak it if we decide to

Thanks for hearing me out, and looking forward to working on this any way.

**Comment by bensheldon** [comment]
No sweat, I've had several people try to tell me otherwise with GoodJob too 😁 that's why I try to let the results speak for themselves.

Having a complete design system, available from the start, without having to make any other changes when implementing a new feature, other than small overrides in a separate file (if that), makes development vastly easier (just like in an application), and features more trivial to implement. That's possible to do without any reliance on the parent-app's asset pipeline ("No Build").

It's not much more complex for CSS. Instead of 1 file, it's 2: `bootstrap.min.css` (which never is modified, other than all-at-once when upgrading to a newer version of bootstrap) and `application.css` (which contains custom overrides, when necessary). 

In GoodJob:

- The static assets themselves in [`app/frontend`](https://github.com/bensheldon/good_job/tree/62af353b863c22301fe20d663e5b798b9477d6cd/app/frontend/good_job). The vast majority are for JS, including Stimulus controllers, (Spectator Sport should probably have Stimulus too). They're in `app/frontend` because `app/assets` is implicitly added to the asset pipeline and that broke some applications. The name doesn't matter, it just can't be `app/assets`.
- The [one controller](https://github.com/bensheldon/good_job/blob/62af353b863c22301fe20d663e5b798b9477d6cd/app/controllers/good_job/frontends_controller.rb). Again, it's largely setting up the JS importmaps that make it complex, though that's also largely static configuration.
- The [routes entry](https://github.com/bensheldon/good_job/blob/62af353b863c22301fe20d663e5b798b9477d6cd/config/routes.rb#L40-L43)
- The [layout `<head>`](https://github.com/bensheldon/good_job/blob/62af353b863c22301fe20d663e5b798b9477d6cd/app/views/layouts/good_job/application.html.erb#L23-L32), which I'll admit is a little gross as a ruby engineer, but not so bad as a frontend developer.

> no idea where to start with your suggested change with Rack::Files

Don't worry about it, I suggested like 5 overlapping things to do 😰 It can be done after the GoodJob-copy is done, or never really (still haven't done it on GoodJob, though obviously it lives in my head as something _to do_.).

**Aside about Bootstrap vs Tailwind:** I will admit my interest in Bootstrap here is maybe anachronistic, cause lots of people love Tailwind, which I'm less familiar with. I believe that to make Tailwind functionally comparable to Bootstrap, one would also need to package a component library alongside Tailwind (now we're talking 3 css files, to be fair), and I'm also not sure if the love for Tailwind (or familiarity) still applies when using Tailwind+Components in a "No Build" approach (i.e., the entire library is vendored without application-specific compilation). I am fully committed to "use boring technology" and Bootstrap is the epitome of boring and I can take the hit on that and I'd rather stand my ground on that than debate, for example, what is the best tailwind component library and whether or not people are familiar with whatever the one is that would be chosen. [Nobody gets fired for choosing Bootstrap.](https://dev.to/bikeshed/58-nobody-gets-fired-for-buying-ibm) 🤣

**Comment by janpeterka** [comment]
Thanks for explanation, and as I used Bootstrap extensively in my projects too, I see the value :)
Ok, when you put it like this, it doesn't seem that complex.

_I mentioned Tailwind as its used in SolidErrors, but (and this might not be clear) my proposition wasn't using Tailwind (which would, as you write, introduce ~same level of complexity and dependance that I'd prefer to not have). So my view was that "the most boring" is just plain css :grin:_

**Comment by bensheldon** [comment]
@janpeterka fyi, I'm gonna do this next on my todo list. I really appreciate all the interest you have (and totally understand if life catches up to you).

**Comment by janpeterka** [comment]
thanks for letting me know, I probably won't get to this any time soon, sorry for that. hope to contribute to other parts later :)
